name: tfsec

on:
  push:
    branches: [ "dev", "staging" ]
  pull_request:
    branches: [ "prod" ]

jobs:
  tfsec:
    name: Run tfsec and generate sarif report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Run tfsec
        run: tfsec --format sarif --out results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
          category: tfsec  # ← ESSA LINHA É CRUCIAL
